### ISSUE TITLE
BUG: relative path import and pip-install

### ISSUE THREAD

**Issue by jklenzing** [drsteve/PyForecastTools#12] opened 2021-09-15 17:56 UTC
After installing from pip, some of the functions such as `bias`, etc, are not attached to `verify` when importing.  After uninstalling from pip and reinstalling from github, all functions are importing correctly.  I suspect that switching to absolute import statements in `init` would fix this on the pip side.

```
from verify.metrics import *
from verify.categorical import *
from verify. import plot
```

**Comment by drsteve** [comment] 2021-09-15 18:52
Thanks @jklenzing  - I'm having trouble reproducing this. I've tried:
- WSL2 (Ubuntu 20.04)
  - conda environment, Python 3.8, pip 21.2.2
  - system python (no env), Python 3.8, pip 20.0.2
- Anaconda, Windows 10, Python 3.7, pip 20.0.2
- RHEL7
  - conda environment, Python 3.7, pip 21.0.1
  - system python (via module), Python 3.9, pip 21.1.3

In each case I made sure PyForecast tools wasn't installed (so two of these include a removal step), then I installed using `pip install PyForecastTools` and launched the Python interpreter.
Then,
```
import verify
verify.bias
```
And in `ipython` I also used `verify.[tab]` to show the list of attributes.
Everything appears to be importing correctly.

Can I get a bit more info to help reproduce the error?
OS, Python version, pip version, use (or not) of conda or venv, ...

Also, if you make a clean virtual environment with either conda or venv do you have the same problem?

**Comment by jklenzing** [comment] 2021-09-15 19:03
Sorry, I should have provided more info above.  I'm using:
Mac OS X 10.15.7
python 3.8.11 installed through conda
pip 20.2.4
Working out of the base environment under conda

I'll poke around later today to see if I can trigger this in another virtual env.

**Comment by jklenzing** [comment] 2021-09-15 22:05
I'm having trouble duplicating this as well. The uninstall and reinstall seems to have solved this, including new pip installs.  My original install was from ages ago, I suspect that along the line changes in either conda or pip must have triggered the issue by breaking a path somewhere.

**Comment by drsteve** [comment] 2021-09-16 00:15
No worries, I'm glad the issue is ~resolved~ no longer present. I've seen import/pathing issues with conda before where a _user install_ was done from a conda environment, but it manifested a little differently to this.

I'll close it, but if you stumble across being able to reproduce it then please reopen!

**Closed by drsteve** 2021-09-16 00:15 UTC
